version: "3.7"
services:
  pytorch-jupyter:
    build:
      context: .
    # enable gpu usage
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # below from https://github.com/iot-salzburg/gpu-jupyter/blob/master/docker-compose.yml
    ports:
      - 127.0.0.1:8848:8888
    volumes:
      - ./src:/home/jovyan/work
      - ./jupyter:/home/jovyan/.jupyter
    environment:
      GRANT_SUDO: "yes"
      JUPYTER_ENABLE_LAB: "yes"
      NB_UID: ${JUPYTER_UID:-1000}
      NB_GID: ${JUPYTER_GID:-1000}
    # enable sudo permissions
    user:
      "root"
    restart: always